apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chat
  labels: {{- include "qiskit-studio.labels" . | nindent 4 }}
    app.kubernetes.io/component: chat
spec:
  type: {{ .Values.chat.service.type }}
  ports:
  - port: {{ .Values.chat.service.port }}
    protocol: TCP
    targetPort: {{ .Values.chat.service.port }}
    {{- if eq .Values.chat.service.type "NodePort" }}
    nodePort: {{ .Values.chat.service.nodePort }}
    {{- end }}
  selector:
    {{- include "qiskit-studio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: chat