{{- if .Values.global.imagePullSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecrets.name }}
  labels:
    {{- include "qiskit-studio.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecrets.value | b64enc | quote }}
{{- end -}}